apiVersion: apps/v1
kind: Deployment
metadata:
  name: byk-widget
spec:
  selector:
    matchLabels:
      app: byk-widget
  template:
    metadata:
      labels:
        app: byk-widget
    spec:
      containers:
        - name: byk-widget
          image: ghcr.io/buerokratt/chat-widget:beta-1.0.1
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: dsl
              mountPath: /usr/share/nginx/html/widget/index.html
              subPath: index.html
            - name: widget-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
          livenessProbe:
            httpGet:
              path: /status
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /status
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
      initContainers:
        - name: dsl-installer
          image: alpine/git:2.36.3
          volumeMounts:
            - name: dsl
              mountPath: /root/DSL
          command: ["/bin/sh"]
          args:
            - "-c"
            - >
              git clone $INDEX_REPO /tmp/index-source &&
              echo 'downloaded' &&
              mv /tmp/index-source/$INDEX_PATH /root/DSL/ &&
              echo 'moved'
          env:
            - name: INDEX_REPO
              value: {{ .Values.byk.widget.index.repo }}
            - name: INDEX_PATH
              value: {{ .Values.byk.widget.index.path }}
      volumes:
        - name: dsl
          emptyDir: {}
        - name: widget-config
          configMap:
            name: widget-nginx-config
